# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Azure Pipelines'
  vmImage: 'Hosted Agent'

steps:
- bash: echo "Our First Pipeline"

